name: Acionar Testes

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Acionar workflow de testes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'kriserdmann',
              repo: 'prova-js-basico-74-testes',
              event_type: 'run-tests',
              client_payload: {
                repository: context.repo.full_name,
                sha: context.sha
              }
            });
