name: Acionar Testes

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Acionar workflow de testes
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: kriserdmann/prova-js-basico-74-testes
          event-type: run-tests
          client-payload: '{"repository": "${{ github.repository }}", "sha": "${{ github.sha }}"}'
